# Generated by Django 3.2 on 2021-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_categoryphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url_link',
            field=models.URLField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=130, null=True),
        ),
    ]
